export const missions = [
    "Rescue a cat stuck in a tree.",
    "Learn to play a musical instrument.",
    "Organize a surprise picnic for a friend.",
    "Help a neighbor build a piece of furniture.",
    "Go for a 10 km hike.",
    "Find and collect 10 different leaves.",
    "Write and send a letter to a stranger.",
    "Learn to juggle.",
    "Plant a tree.",
    "Create a new recipe for food or drinks.",
    "Take a dance class.",
    "Write a poem about your favorite place.",
    "Visit a museum or art gallery.",
    "Build a birdhouse.",
    "Take a first aid course.",
    "Discover a new hiking trail.",
    "Complete a challenging jigsaw puzzle.",
    "Learn to do origami.",
    "Go on a day trip to a nearby city.",
    "Practice meditation for 30 minutes every day for a week.",
    "Write a journal for a whole month.",
    "Learn magic tricks.",
    "Visit an amusement park and ride all the roller coasters.",
    "Do an outdoor drawing or painting.",
    "Participate in an escape room game.",
    "Learn to juggle with fire.",
    "Help clean up a beach or local park.",
    "Have a backyard camping trip.",
    "Create a photo album with special moments.",
    "Learn to juggle with knives.",
    "Collect and donate clothes to a charity.",
    "Visit a wildlife park or zoo.",
    "Take an outdoor yoga class.",
    "Learn to knit or crochet.",
    "Join a 5 km race event.",
    "Help build a house for a needy family.",
    "Take a cooking class for an exotic dish.",
    "Learn magic tricks with cards.",
    "Go on a boat or canoe trip.",
    "Create a home garden.",
    "Learn to make balloon sculptures.",
    "Visit a national park.",
    "Help paint a mural on a community wall.",
    "Take a photography class and take amazing photos.",
    "Learn juggling tricks with balls.",
    "Join a martial arts class.",
    "Complete a 1000-piece jigsaw puzzle.",
    "Help organize a charity event.",
    "Have a starlit picnic.",
    "Paint a house",
    "Run for president",
    "Compete in a superhero costume fashion show.",
    "Have a dance-off with the villains.",
    "Participate in a hot dog eating contest.",
    "Go on a road trip in the superhero-mobile.",
    "Challenge each other to a thumb wrestling match.",
    "Attend a superhero-themed karaoke night.",
    "Have a paintball battle against the villains.",
    "Attempt to break a world record together.",
    "Organize a superhero-themed surprise party for a friend.",
    "Play a game of superhero trivia.",
    "Create a superhero-themed TikTok dance routine.",
    "Have a water balloon fight in superhero costumes.",
    "Go on a mission to find the best pizza in town.",
    "Compete in a superhero-themed cooking competition.",
    "Try to solve a superhero-themed escape room.",
    "Go on a city-wide scavenger hunt.",
    "Participate in a superhero-themed charity run.",
    "Challenge each other to a superhero-themed rap battle.",
    "Have a superhero-themed movie marathon.",
    "Build a superhero-themed sandcastle at the beach.",
    "Try to catch a villain using a disguise and secret identities.",
    "Go on a superhero-themed shopping spree.",
    "Take superhero-themed flying lessons.",
    "Participate in a superhero-themed obstacle course race.",
    "Have a superhero-themed paint night.",
    "Go undercover as civilians and try to blend in with the crowd.",
    "Challenge each other to a superhero-themed arm wrestling match.",
    "Organize a superhero-themed magic show for kids.",
    "Play a superhero-themed board game tournament.",
    "Go on a superhero-themed photo shoot in iconic locations.",
    "Try to outdo each other in a superhero-themed talent show.",
    "Compete in a superhero-themed mini-golf tournament.",
    "Have a superhero-themed picnic in the park.",
    "Go on a mission to rescue a stolen superhero cape.",
    "Challenge each other to a superhero-themed video game tournament.",
    "Try to teach each other a new superhero skill.",
    "Participate in a superhero-themed dance marathon.",
    "Organize a superhero-themed beach party.",
    "Go on a mission to find the best superhero-themed ice cream shop.",
    "Challenge each other to a superhero-themed puzzle-solving contest.",
    "Have a superhero-themed photo booth session.",
    "Go on a mission to capture a mischievous superpowered pet.",
    "Participate in a superhero-themed talent show.",
    "Challenge each other to a superhero-themed arm wrestling match.",
    "Organize a superhero-themed magic show for kids.",
    "Play a superhero-themed board game tournament.",
    "Go on a superhero-themed photo shoot in iconic locations.",
    "Try to outdo each other in a superhero-themed talent show.",
    "Compete in a superhero-themed mini-golf tournament.",
    "Have a superhero-themed picnic in the park.",
    "Go on a mission to rescue a stolen superhero cape.",
    "Challenge each other to a superhero-themed video game tournament.",
    "Try to teach each other a new superhero skill.",
    "Participate in a superhero-themed dance marathon.",
    "Organize a superhero-themed beach party.",
    "Go on a mission to find the best superhero-themed ice cream shop.",
    "Challenge each other to a superhero-themed puzzle-solving contest.",
    "Have a superhero-themed photo booth session.",
    "Go on a mission to capture a mischievous superpowered pet.",
    "Participate in a superhero-themed talent show."
]